---
- hosts: all
  tasks:
  - name: "Update Repository cache"
    apt:
      update_cache: true
      cache_valid_time: 3600
      force_apt_get: true
- hosts: all
  tasks:
  - name: Package installation
    apt:
      name:
        - git
        - curl
        - wget
        - python3-pip
      state: latest
- name: Installing Nvidia GPU
  hosts: all
  become: true
  become_user: root
  tasks:
    - name : Initiating Nvidia GPU
      shell : apt-get install linux-headers-$(uname -r) && distribution=$(. /etc/os-release;echo $ID$VERSION_ID | sed -e 's/\.//g') && wget https://developer.download.nvidia.com/compute/cuda/repos/$distribution/x86_64/cuda-keyring_1.0-1_all.deb && dpkg -i cuda-keyring_1.0-1_all.deb && sudo apt-get update
- hosts: all
  tasks:
  - name: Install Cuda Drivers
    apt:
      name:
        - cuda-drivers
      state: latest
# - name: Installing Nvidia Docker
#   hosts: all
#   become: true
#   become_user: root
#   tasks:
#     - name : Initiating Nvidia Docker
#       shell : distribution=$(. /etc/os-release;echo $ID$VERSION_ID)    && curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | apt-key add -    && curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | tee /etc/apt/sources.list.d/nvidia-docker.list && apt-get update && apt-get install -y nvidia-docker2
